# Generated by Django 3.1.5 on 2023-05-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DynamoDiviaky', '0002_auto_20230526_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypZapasu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazov', models.CharField(max_length=50, verbose_name='Názov')),
            ],
        ),
        migrations.AddField(
            model_name='rezervacie',
            name='plocha',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='DynamoDiviaky.hracieplochy'),
        ),
        migrations.AddField(
            model_name='rezervacie',
            name='typzapasu',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='DynamoDiviaky.typzapasu'),
        ),
    ]
