# Generated by Django 3.1.5 on 2023-05-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DynamoDiviaky', '0003_auto_20230526_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezervacie',
            old_name='plocha',
            new_name='hracieplochy',
        ),
    ]
