# Generated by Django 3.2.19 on 2023-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamoDiviaky', '0004_auto_20230526_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervacie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
