# Generated by Django 3.2.19 on 2023-06-01 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DynamoDiviaky', '0005_alter_rezervacie_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hrci',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hrac', models.CharField(max_length=80, verbose_name='Celé meno')),
                ('meno', models.CharField(max_length=80, verbose_name='Meno')),
                ('priezvisko', models.CharField(max_length=80, verbose_name='Priezvisko')),
                ('matersky_klub', models.CharField(max_length=50, verbose_name='Materský klub')),
                ('hostujuci_klub', models.CharField(max_length=50, verbose_name='Hosťujúci klub')),
                ('klubova_prislusnost', models.CharField(max_length=50, verbose_name='Klubová príslušnosť')),
                ('hostovanie', models.CharField(max_length=50, verbose_name='Hosťovanie')),
                ('clenske_od', models.DateField(verbose_name='Členské od')),
                ('clenske_do', models.DateField(verbose_name='Členské do')),
                ('registracne_cislo', models.CharField(max_length=12, verbose_name='Registračné číslo')),
                ('datum_narodenia', models.DateField(verbose_name='Dátum narodenia')),
                ('platnost_rp', models.DateField(verbose_name='Platnosť reg.preukazu')),
                ('stav', models.CharField(max_length=12, verbose_name='Stav')),
                ('tim', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='DynamoDiviaky.timy')),
            ],
        ),
    ]
