# Generated by Django 3.2.19 on 2023-06-01 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DynamoDiviaky', '0006_hrci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrci',
            name='tim',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DynamoDiviaky.timy'),
        ),
    ]
