# Generated by Django 3.2.19 on 2023-06-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DynamoDiviaky', '0007_alter_hrci_tim'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hrci',
            new_name='Hraci',
        ),
    ]
