# Generated by Django 3.2.19 on 2023-06-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamoDiviaky', '0009_alter_timy_skratka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
