# Generated by Django 3.2.19 on 2023-06-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamoDiviaky', '0010_alter_timy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hraci',
            name='registracne_cislo',
            field=models.CharField(max_length=12, unique=True, verbose_name='Registračné číslo'),
        ),
    ]
