# Generated by Django 3.2.19 on 2023-06-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DynamoDiviaky', '0012_remove_hraci_tim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hraci',
        ),
    ]
