# Generated by Django 3.2.19 on 2023-06-02 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DynamoDiviaky', '0014_alter_timy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervacie',
            name='tim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DynamoDiviaky.timy'),
        ),
    ]
