# Generated by Django 3.2.19 on 2023-06-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamoDiviaky', '0015_alter_rezervacie_tim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='timy',
            name='nazov',
            field=models.CharField(max_length=50, unique=True, verbose_name='Názov'),
        ),
    ]
