# Generated by Django 3.2.19 on 2023-06-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamoDiviaky', '0016_auto_20230602_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervacie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
