# Generated by Django 3.2.19 on 2023-06-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamoDiviaky', '0017_alter_rezervacie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timy',
            name='nazov',
            field=models.CharField(max_length=50, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='timy',
            name='skratka',
            field=models.CharField(max_length=5, verbose_name='Skratka'),
        ),
    ]
